# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-23 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_notifications_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='sent_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
