# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0003_users_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankemployee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
