# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0004_bankemployee_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_core.Bank')),
            ],
        ),
    ]
