# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-20 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
